smtp:
  host: smtp.gmail.com
  port: 587
  username: quadev.ltd.10808171@gmail.com
  password: mfybcxdrxkmtjzfa
aws:
  aws_key: AKIARWDSJ2CMK4KP3ASZ
  aws_secret: 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